reconstruction and expansion of services

diff --git a/src/bash/config-init b/src/bash/config-init
--- a/src/bash/config-init
+++ b/src/bash/config-init
@@ -4,16 +4,21 @@ set -eo pipefail
 # CHECK PREREQUIREMENTS
 # - grep
 #========
-for cmd in grep
-do
-  command -v ${cmd} > /dev/null || {  echo >&2 "${cmd} must be installed - exiting..."; exit 1; }
+for cmd in grep; do
+  command -v ${cmd} >/dev/null || {
+    echo >&2 "${cmd} must be installed - exiting..."
+    exit 1
+  }
 done
 
 #========
 # DEFAULTS
 # - all related default values inside this script
 #========
-SCRIPT_DIR="$(cd "$(dirname "$0")" ; pwd -P)"
+SCRIPT_DIR="$(
+  cd "$(dirname "$0")"
+  pwd -P
+)"
 PWD="$(pwd -P)"
 DEFAULT_TARGET_FILENAME="config"
 DEFAULT_TARGET_PATH="${PWD}"
@@ -23,19 +28,19 @@ DEFAULT_FORCE=0
 # FUNCTIONS
 #========
 function infoEcho {
-    echo "INFO: ${1}" 1>&2
+  echo "INFO: ${1}" 1>&2
 }
 
 function errorEcho {
-    echo "ERROR: ${1}" 1>&2
-    exit 1
+  echo "ERROR: ${1}" 1>&2
+  exit 1
 }
 
 function errorUsage {
-    echo "ERROR: ${1}" 1>&2
-    echo ""
-    usage
-    exit 1
+  echo "ERROR: ${1}" 1>&2
+  echo ""
+  usage
+  exit 1
 }
 
 function usage() {
@@ -57,29 +62,30 @@ function usage() {
 # SCRIPT
 #========
 while [[ $# -gt 0 ]]; do
-    key="${1}"
+  key="${1}"
 
-    case $key in
-        --target-path|-t)
-        shift
-        export TARGET_PATH="${1}"
-        shift
-        ;;
-        --filename|-n)
-        shift
-        export TARGET_FILENAME="${1}"
-        ;;
-        --force|-f)
-        shift
-        export FORCE=1
-        ;;
-        --help|-h|help)
-        usage
-        exit 0
-        ;;
-        *)
-        shift
-    esac
+  case $key in
+  --target-path | -t)
+    shift
+    export TARGET_PATH="${1}"
+    shift
+    ;;
+  --filename | -n)
+    shift
+    export TARGET_FILENAME="${1}"
+    ;;
+  --force | -f)
+    shift
+    export FORCE=1
+    ;;
+  --help | -h | help)
+    usage
+    exit 0
+    ;;
+  *)
+    shift
+    ;;
+  esac
 done
 
 # Assign default values if optional argument is empty
@@ -91,7 +97,7 @@ for variable in TARGET_PATH TARGET_FILENAME FORCE; do
 done
 
 # Check for existing config file at given path
-if [ -f "${TARGET_PATH}/${TARGET_FILENAME}.yaml" ] && [ "${FORCE}" -ne "1"  ]; then
+if [ -f "${TARGET_PATH}/${TARGET_FILENAME}.yaml" ] && [ "${FORCE}" -ne "1" ]; then
   errorEcho "Config file ${TARGET_PATH}/${TARGET_FILENAME}.yaml already exists and FORCE is not enabled. Delete file to generate new one!"
 else
   infoEcho "Copied initial config file to ${TARGET_PATH}/${TARGET_FILENAME}.yaml"
diff --git a/src/bash/config-pull b/src/bash/config-pull
--- a/src/bash/config-pull
+++ b/src/bash/config-pull
@@ -11,7 +11,7 @@ function interactive {
     REPLY=""
     while [[ -z "${REPLY}" ]]; do
       echo -n "${variable}: "
-      read;
+      read
     done
     export "${variable}=${REPLY}"
   done
@@ -29,29 +29,29 @@ function interactive {
   select yn in "yes" "no"; do
     case $yn in
     yes)
-    return
-    ;;
+      return
+      ;;
     no)
-    errorEcho "User aborted script."
-    ;;
+      errorEcho "User aborted script."
+      ;;
     esac
   done
 }
 
 function infoEcho {
-    echo "INFO: ${1}" 1>&2
+  echo "INFO: ${1}" 1>&2
 }
 
 function errorEcho {
-    echo "ERROR: ${1}" 1>&2
-    exit 1
+  echo "ERROR: ${1}" 1>&2
+  exit 1
 }
 
 function errorUsage {
-    echo "ERROR: ${1}" 1>&2
-    echo ""
-    usage
-    exit 1
+  echo "ERROR: ${1}" 1>&2
+  echo ""
+  usage
+  exit 1
 }
 
 # load env file if present
@@ -62,79 +62,82 @@ if [[ -f "${PWD}/.tanzu-creator" ]]; then
 fi
 
 # check prerequisites
-for cmd in jq az
-do
-  command -v ${cmd} > /dev/null || {  echo >&2 "${cmd} must be installed - exiting..."; exit 1; }
+for cmd in jq az; do
+  command -v ${cmd} >/dev/null || {
+    echo >&2 "${cmd} must be installed - exiting..."
+    exit 1
+  }
 done
 
 DEFAULT_CONFIG_FILE="${PWD}/config.yaml"
 DEFAULT_FORCE=0
 DEFAULT_INTERACTIVE=0
 function usage() {
-echo "Download the config.yaml from your Azure KeyVault."
-echo ""
-echo "usage: $0 [options]"
-echo ""
-echo "        -c --config-file <path>:      Path to the target config file to be saved (default: ${DEFAULT_CONFIG_FILE}) (ENV: CONFIG_FILE)"
-echo "        -f --force:                   Overwrite exiting config file (default: ${DEFAULT_FORCE}) (ENV: FORCE)"
-echo "        -i --interactive:             Starts this script in interactive mode (default: ${DEFAULT_INTERACTIVE}) (ENV: INTERACTIVE)"
-echo "        -n --filename:                Filename to pulled config file (default: ${DEFAULT_TARGET_FILENAME}) (ENV: TARGET_FILENAME)"
-echo ""
-echo "        -s --subscription:            The Azure subscription used for login (required) (ENV: SUBSCRIPTION)"
-echo "        -k --key-vault-name <name>:   Name of the key vault containing the secret (required) (ENV: KEY_VAULT_NAME)"
-echo "        -e --secret-name <name>:      Name of the secret containing the config file (required) (ENV: SECRET_NAME)"
-echo ""
-echo "environment variables:"
-echo ""
-echo "        CONFIG_FILE <path>:           Path to the destination at which the config file will be stored (default: ${DEFAULT_CONFIG_FILE})"
-echo "        FORCE <0|1>:                  Overwrite exiting config file (default: ${DEFAULT_FORCE})"
-echo "        INTERACTIVE <0|1>:            Starts this script in interactive mode (default: ${DEFAULT_INTERACTIVE})"
-echo ""
-echo "        SUBSCRIPTION <id>:            The Azure subscription used for login (required)"
-echo "        KEY_VAULT_NAME <name>:        Name of the key vault containing the secret (required)"
-echo "        SECRET_NAME <name>:           Name of the secret containing the config file (required)"
+  echo "Download the config.yaml from your Azure KeyVault."
+  echo ""
+  echo "usage: $0 [options]"
+  echo ""
+  echo "        -c --config-file <path>:      Path to the target config file to be saved (default: ${DEFAULT_CONFIG_FILE}) (ENV: CONFIG_FILE)"
+  echo "        -f --force:                   Overwrite exiting config file (default: ${DEFAULT_FORCE}) (ENV: FORCE)"
+  echo "        -i --interactive:             Starts this script in interactive mode (default: ${DEFAULT_INTERACTIVE}) (ENV: INTERACTIVE)"
+  echo "        -n --filename:                Filename to pulled config file (default: ${DEFAULT_TARGET_FILENAME}) (ENV: TARGET_FILENAME)"
+  echo ""
+  echo "        -s --subscription:            The Azure subscription used for login (required) (ENV: SUBSCRIPTION)"
+  echo "        -k --key-vault-name <name>:   Name of the key vault containing the secret (required) (ENV: KEY_VAULT_NAME)"
+  echo "        -e --secret-name <name>:      Name of the secret containing the config file (required) (ENV: SECRET_NAME)"
+  echo ""
+  echo "environment variables:"
+  echo ""
+  echo "        CONFIG_FILE <path>:           Path to the destination at which the config file will be stored (default: ${DEFAULT_CONFIG_FILE})"
+  echo "        FORCE <0|1>:                  Overwrite exiting config file (default: ${DEFAULT_FORCE})"
+  echo "        INTERACTIVE <0|1>:            Starts this script in interactive mode (default: ${DEFAULT_INTERACTIVE})"
+  echo ""
+  echo "        SUBSCRIPTION <id>:            The Azure subscription used for login (required)"
+  echo "        KEY_VAULT_NAME <name>:        Name of the key vault containing the secret (required)"
+  echo "        SECRET_NAME <name>:           Name of the secret containing the config file (required)"
 }
 
 while [[ $# -gt 0 ]]; do
-    key="${1}"
+  key="${1}"
 
-    case $key in
-        --config-file|-c)
-        shift
-        export CONFIG_FILE="${1}"
-        shift
-        ;;
-        --filename|-n)
-        shift
-        export TARGET_FILENAME="${1}"
-        ;;
-        --force|-f)
-        shift
-        export FORCE=1
-        ;;
-        --interactive|-i)
-        shift
-        export INTERACTIVE=1
-        ;;
-        --subscription|-s)
-        shift
-        export SUBSCRIPTION="${1}"
-        ;;
-        --key-vault-name|-k)
-        shift
-        export KEY_VAULT_NAME="${1}"
-        ;;
-        --secret-name|-e)
-        shift
-        export SECRET_NAME="${1}"
-        ;;
-        --help|-h|help)
-        usage
-        exit 0
-        ;;
-        *)
-        shift
-    esac
+  case $key in
+  --config-file | -c)
+    shift
+    export CONFIG_FILE="${1}"
+    shift
+    ;;
+  --filename | -n)
+    shift
+    export TARGET_FILENAME="${1}"
+    ;;
+  --force | -f)
+    shift
+    export FORCE=1
+    ;;
+  --interactive | -i)
+    shift
+    export INTERACTIVE=1
+    ;;
+  --subscription | -s)
+    shift
+    export SUBSCRIPTION="${1}"
+    ;;
+  --key-vault-name | -k)
+    shift
+    export KEY_VAULT_NAME="${1}"
+    ;;
+  --secret-name | -e)
+    shift
+    export SECRET_NAME="${1}"
+    ;;
+  --help | -h | help)
+    usage
+    exit 0
+    ;;
+  *)
+    shift
+    ;;
+  esac
 done
 
 # Assign default values if optional argument is empty
@@ -154,7 +157,7 @@ for variable in SUBSCRIPTION KEY_VAULT_NAME SECRET_NAME; do
 done
 
 # save to env file
-cat <<EOF > "${PWD}/.tanzu-creator"
+cat <<EOF >"${PWD}/.tanzu-creator"
 SUBSCRIPTION=${SUBSCRIPTION}
 KEY_VAULT_NAME=${KEY_VAULT_NAME}
 SECRET_NAME=${SECRET_NAME}
@@ -183,8 +186,8 @@ az account set --subscription "${SUBSCRIPTION}"
 infoEcho "Pulling configuration file from KeyVault '${KEY_VAULT_NAME}' and secret '${SECRET_NAME}'"
 az keyvault secret show \
   --name "${SECRET_NAME}" \
-  --vault-name "${KEY_VAULT_NAME}" \
-  | jq -r .value \
-  > "${TARGET_FILENAME}"
+  --vault-name "${KEY_VAULT_NAME}" |
+  jq -r .value \
+    >"${TARGET_FILENAME}"
 
 infoEcho "Success."
